### ISSUE TITLE
Question: why fxhash ?

### ISSUE THREAD

**Issue by thomvil** [willcrichton/indexical#1]
I found this crate by reading your [blogpost](https://willcrichton.net/notes/k-corrset/) Kudos, i much enjoyed it!

I noticed you depend on [fxhash](https://crates.io/crates/fxhash/). I thought was designed for highly specific use-cases, and is vulnerable to collisions in many others? Did you choose `fxhash` specifically over alternatives as [ahash](https://crates.io/crates/ahash)?

If you could find the time, would you consider explaining a little about this choice?

Thanks in advance

**Comment by willcrichton** [comment]
Fxhash was just a fast hasher I knew off the top of my head. I'll have to check out ahash.
